<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Solarpunk.Persistence</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Dapper" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Solarpunk.Abstractions/Solarpunk.Abstractions.csproj" />
  </ItemGroup>
</Project>
