<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Solarpunk.Protocol</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="MessagePackAnalyzer">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
